# Generated by Django 4.2.16 on 2024-10-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hiragana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('romaji', models.CharField(max_length=10)),
                ('kana', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Katakana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('romaji', models.CharField(max_length=10)),
                ('kana', models.CharField(max_length=10)),
            ],
        ),
    ]
